enum EducationLevelValue {
  PRIMARY_SCHOOL = 'PRIMARY_SCHOOL',
  SECONDARY_SCHOOL_NO_EXAMS = 'SECONDARY_SCHOOL_NO_EXAMS',
  SECONDARY_SCHOOL_EXAMS = 'SECONDARY_SCHOOL_EXAMS',
  FURTHER_EDUCATION_COLLEGE = 'FURTHER_EDUCATION_COLLEGE',
  UNDERGRADUATE_DEGREE = 'UNDERGRADUATE_DEGREE',
  POSTGRADUATE_DEGREE = 'POSTGRADUATE_DEGREE',
  NOT_SURE = 'NOT_SURE',
}

export default EducationLevelValue
