import { stubFor } from './wiremock'
import prisoners from '../mockData/prisonerByIdData'
import ciagPrisoners from '../mockData/ciagListData'

const getPrisonerById = (id = 'G6115VJ') => stubFor(prisoners[id])

const getPrisonersByCaseloadId = (caseloadId: string) =>
  stubFor({
    request: {
      method: 'GET',
      url: `/prisoner-search/prison/${caseloadId}?page=0&size=2000`,
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        content: [
          {
            prisonerNumber: 'A0670DZ',
            firstName: 'MILO',
            lastName: 'CATTUS',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-01-24',
          },
          {
            prisonerNumber: 'A0772DZ',
            firstName: 'JOHN',
            lastName: 'DAVIES',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-01-27',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
          {
            prisonerNumber: 'A1749DZ',
            firstName: 'JOYCE',
            lastName: 'GLEASON',
            releaseDate: '2023-05-28',
            nonDtoReleaseDate: '2023-05-13',
            nonDtoReleaseDateType: 'ARD',
            receptionDate: '2023-03-10',
          },
        ],
        pageable: {
          sort: { empty: true, sorted: false, unsorted: true },
          offset: 0,
          pageNumber: 0,
          pageSize: 3,
          paged: true,
          unpaged: false,
        },
        totalElements: 1041,
        last: false,
        totalPages: 347,
        size: 3,
        number: 0,
        sort: { empty: true, sorted: false, unsorted: true },
        first: true,
        numberOfElements: 3,
        empty: false,
      },
    },
  })

export default {
  getPrisonerById,
  getPrisonersByCaseloadId,
}
