---
# Per environment values which override defaults in hmpps-ciag-careers-induction-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
	host: hmpps-ciag-careers-induction-ui-preprod.hmpps.service.justice.gov.uk

  env:
	INGRESS_URL: "https://hmpps-ciag-careers-induction-ui-preprod.hmpps.service.justice.gov.uk"
	HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
	TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
        HMPPS_PRISON_API_URL: "https://api-dev.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
