---
# Per environment values which override defaults in hmpps-ciag-careers-induction-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: ciag-induction-dev.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: dev
    ENVIRONMENT_NAME: 'DEV'
    S3_REGION: eu-west-2
    INGRESS_URL: "https://ciag-induction-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-dev.prison.service.justice.gov.uk"
    COMMUNITY_API_URL: "https://community-api-public.dev.probation.service.justice.gov.uk"
    CURIOUS_API_URL: "https://testservices.sequation.net/sequation-virtual-campus2-api/"
    PRISONER_SEARCH_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-dev.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api-dev.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://allocation-manager-staging.apps.live.cloud-platform.service.justice.gov.uk"
    CIAG_API_URL: "https://ciag-induction-api-dev.hmpps.service.justice.gov.uk"
    LEARNING_AND_WORK_PROGRESS_URL: "https://learning-and-work-progress-dev.hmpps.service.justice.gov.uk"
    EDUCATION_AND_WORK_PLAN_API: "https://learningandworkprogress-api-dev.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk/feedback-and-support"
    MANAGE_USERS_API: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: DEV

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
