---
# Per environment values which override defaults in hmpps-ciag-careers-induction-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: ciag-induction-preprod.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: preprod
    S3_REGION: eu-west-2
    INGRESS_URL: "https://ciag-induction-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk"
    COMMUNITY_API_URL: "https://community-api-public.preprod.probation.service.justice.gov.uk"
    CURIOUS_API_URL: "https://preprodservices.sequation.net/sequation-virtual-campus2-api/"
    PRISONER_SEARCH_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
    KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk"
    WHEREABOUTS_API_URL: "https://whereabouts-api-preprod.service.justice.gov.uk"
    ALLOCATION_MANAGER_ENDPOINT_URL: "https://allocation-manager-preprod.apps.live.cloud-platform.service.justice.gov.uk"
    CIAG_API_URL: "https://ciag-induction-api-preprod.hmpps.service.justice.gov.uk"
    LEARNING_AND_WORK_PROGRESS_URL: "https://learning-and-work-progress-ui-preprod.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: PREPROD

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
