const plans = {
  A00001A: {
    request: {
      method: 'GET',
      urlPattern: '/ciag/induction/A00001A',
    },
    response: {
      status: 404,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        status: 404,
        userMessage: 'CIAG profile does not exist',
      },
    },
  },
  G6115VJ: {
    request: {
      method: 'GET',
      urlPattern: '/ciag/induction/G6115VJ',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        offenderId: 'G6115VJ',
      },
    },
  },
  A3260DZ: {
    request: {
      method: 'GET',
      urlPattern: '/ciag/induction/A3260DZ',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        offenderId: 'A3260DZ',
        desireToWork: true,
        hopingToGetWork: 'YES',
        abilityToWork: ['LIMITED_BY_OFFENSE', 'CARING_RESPONSIBILITIES', 'HEALTH_ISSUES', 'NO_RIGHT_TO_WORK', 'OTHER'],
        abilityToWorkOther: 'Some text',
        createdBy: 'GDUTTON_GEN',
        createdDateTime: '2023-10-18T15:23:18.522Z',
        modifiedBy: 'GDUTTON_GEN',
        modifiedDateTime: '2023-10-18T15:23:18.522Z',
        workExperience: {
          hasWorkedBefore: true,
          typeOfWorkExperience: [
            'BEAUTY',
            'CLEANING_AND_MAINTENANCE',
            'CONSTRUCTION',
            'DRIVING',
            'EDUCATION_TRAINING',
            'HOSPITALITY',
            'MANUFACTURING',
            'OFFICE',
            'OTHER',
            'OUTDOOR',
            'RETAIL',
            'SPORTS',
            'TECHNICAL',
            'WAREHOUSING',
            'WASTE_MANAGEMENT',
          ],
          typeOfWorkExperienceOther: 'Some text',
          workExperience: [
            { typeOfWorkExperience: 'BEAUTY', role: 'Some role', details: 'Some text', otherWork: '' },
            {
              typeOfWorkExperience: 'CLEANING_AND_MAINTENANCE',
              role: 'Some role',
              details: 'Some text',
              otherWork: '',
            },
            { typeOfWorkExperience: 'CONSTRUCTION', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'DRIVING', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'EDUCATION_TRAINING', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'HOSPITALITY', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'MANUFACTURING', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'OFFICE', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'OTHER', role: 'Some role', details: 'Some text', otherWork: 'Some text' },
            { typeOfWorkExperience: 'OUTDOOR', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'RETAIL', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'SPORTS', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'TECHNICAL', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'WAREHOUSING', role: 'Some role', details: 'Some text', otherWork: '' },
            { typeOfWorkExperience: 'WASTE_MANAGEMENT', role: 'Some role', details: 'Some text', otherWork: '' },
          ],
          modifiedBy: 'GDUTTON_GEN',
          modifiedDateTime: '2023-10-18T15:23:18.522Z',
          workInterests: {
            workInterests: [
              'OUTDOOR',
              'CLEANING_AND_MAINTENANCE',
              'CONSTRUCTION',
              'DRIVING',
              'BEAUTY',
              'HOSPITALITY',
              'TECHNICAL',
              'MANUFACTURING',
              'OFFICE',
              'RETAIL',
              'SPORTS',
              'EDUCATION_TRAINING',
              'WAREHOUSING',
              'WASTE_MANAGEMENT',
              'OTHER',
            ],
            workInterestsOther: 'Some text',
            particularJobInterests: [
              {
                workInterest: 'OUTDOOR',
                jobRole: 'Some job role',
              },
            ],
            modifiedBy: 'GDUTTON_GEN',
            modifiedDateTime: '2023-10-18T15:23:18.522Z',
          },
        },
        skillsAndInterests: {
          skills: [
            'COMMUNICATION',
            'POSITIVE_ATTITUDE',
            'RESILIENCE',
            'SELF_MANAGEMENT',
            'TEAMWORK',
            'THINKING_AND_PROBLEM_SOLVING',
            'WILLINGNESS_TO_LEARN',
            'OTHER',
          ],
          skillsOther: 'Some text',
          personalInterests: [
            'COMMUNITY',
            'CRAFTS',
            'CREATIVE',
            'DIGITAL',
            'KNOWLEDGE_BASED',
            'MUSICAL',
            'OUTDOOR',
            'NATURE_AND_ANIMALS',
            'SOCIAL',
            'SOLO_ACTIVITIES',
            'SOLO_SPORTS',
            'TEAM_SPORTS',
            'WELLNESS',
            'OTHER',
          ],
          personalInterestsOther: 'Some text',
          modifiedBy: 'GDUTTON_GEN',
          modifiedDateTime: '2023-10-18T15:23:18.522Z',
        },
        qualificationsAndTraining: {
          educationLevel: 'SECONDARY_SCHOOL_TOOK_EXAMS',
          qualifications: [
            { id: '74bc1ee2-1658-4417-8d31-eafb5e5a7f7f', level: 'LEVEL_2', subject: 'English', grade: 'C' },
          ],
          additionalTraining: [
            'CSCS_CARD',
            'FIRST_AID_CERTIFICATE',
            'FOOD_HYGIENE_CERTIFICATE',
            'FULL_UK_DRIVING_LICENCE',
            'HEALTH_AND_SAFETY',
            'HGV_LICENCE',
            'MACHINERY_TICKETS',
            'MANUAL_HANDLING',
            'TRADE_COURSE',
            'OTHER',
          ],
          additionalTrainingOther: 'Some text',
          modifiedBy: 'GDUTTON_GEN',
          modifiedDateTime: '2023-10-18T15:23:18.522Z',
        },
        inPrisonInterests: {
          inPrisonWork: [
            'CLEANING_AND_HYGIENE',
            'COMPUTERS_OR_DESK_BASED',
            'GARDENING_AND_OUTDOORS',
            'KITCHENS_AND_COOKING',
            'MAINTENANCE',
            'PRISON_LAUNDRY',
            'PRISON_LIBRARY',
            'TEXTILES_AND_SEWING',
            'WELDING_AND_METALWORK',
            'WOODWORK_AND_JOINERY',
            'OTHER',
          ],
          inPrisonWorkOther: 'Some text',

          inPrisonEducation: [
            'BARBERING_AND_HAIRDRESSING',
            'CATERING',
            'COMMUNICATION_SKILLS',
            'ENGLISH_LANGUAGE_SKILLS',
            'FORKLIFT_DRIVING',
            'INTERVIEW_SKILLS',
            'MACHINERY_TICKETS',
            'NUMERACY_SKILLS',
            'RUNNING_A_BUSINESS',
            'SOCIAL_AND_LIFE_SKILLS',
            'WELDING_AND_METALWORK',
            'WOODWORK_AND_JOINERY',
            'OTHER',
          ],
          inPrisonEducationOther: 'Some text',
          modifiedBy: 'GDUTTON_GEN',
          modifiedDateTime: '2023-10-18T15:23:18.522Z',
        },
      },
    },
  },
}

export default plans
